version: "3"
services:

  tmodloader:
    image: terraria_mio
    restart: unless-stopped
    ports:
      - '7777:7777'
    environment:
      - TERRARIA_VER=1353
      - TMOD_VER=0.11.8
    volumes:
      - ./terraria:/terraria
      - ./server:/terrariaServer
    tty: true
    stdin_open: true
    