version: "3"
services:

  tmodloader:
    image: gravityl/tmodloader:latest
    restart: unless-stopped
    ports:
      - '7777:7777'
    environment:
      - TERRARIA_VER=1436
      - TMOD_VER=2022.06.96.4
      - MODS=TMOD
    volumes:
      - ./terraria:/terraria
    tty: true
    stdin_open: true
    
